index: email_links
type: email_link

similar_search_hash:
  size: 16
  filter:
    bool:
      must_not:
        - missing:
            field: accepted
  query:
    match:
      title: <%= query_interpolations[:title] %>
