index: email_links
type: email_link


all:
  size: 20_000

undecided:
  size: 1600
  sort:
    created_at:
      order: asc
  filter:
    and:
      - range:
          created_at:
            gte: 'now-1w'
            time_zone: "+4:00"
      - missing:
          field: accepted
      - exists:
          field: cnt_title_words

unengineered:
  size: 2000
  filter:
    bool:
      must:
        - missing:
            field: cnt_title_words
unread:
  filter:
    bool:
      must:
        - term:
            accepted: true
        - missing:
            field: read

whoops:
  size: 1000
  query:
    bool:
      must:
        - term:
            accepted: false
        - range:
            accept_or_reject_dttm:
              gte: "2016-01-29"
