index: email_links
type: email_link

all:
  body:
    size: 400

undecided:
  size: 400
  sort:
    created_at:
      order: asc
  filter:
    missing:
      field: accepted

unread:
  filter:
    bool:
      must:
        - term:
            accepted: true
        - missing:
            field: read
