index: email_links
type: email_link

all:
  body:

undecided:
  filter:
    missing:
      field: accepted

unread:
  filter:
    bool:
      must:
        - term:
            accepted: true
        - missing:
            field: read
