index: email_links
type: email_link

all:
  size: 20_000

undecided:
  size: 400
  sort:
    created_at:
      order: asc
  filter:
    missing:
      field: accepted

unengineered:
  size: 2000
  filter:
    bool:
      must:
        - missing:
            field: cnt_title_words
unread:
  filter:
    bool:
      must:
        - term:
            accepted: true
        - missing:
            field: read
